### ISSUE TITLE
Windows Version when downloaded doesn't load API requests.

### ISSUE THREAD

**Issue by amazinigmech2418** [heb12/heb12#1]
There are errors for the API requests to get the bible verses from both the JSON files and the Bible API site.

**Comment by MasterOfTheTiger** [comment]
Can you give me more information? Maybe press `CTRL + SHIFT + I` and look at the debugger when trying to fetch it, and then post them here. 

Thanks!

**Comment by MasterOfTheTiger** [comment]
@amazinigmech2418 You said that both cause issues? I can understand the request to the Bible API site not working, but not the JSON files.

**Comment by amazinigmech2418** [comment]
@MasterOfTheTiger It says something about cross-origin requests.

**Comment by MasterOfTheTiger** [comment]
@amazinigmech2418 Cross-origin requests. Oh, are you still having that trouble? If so, we need to figure out how to edit the request settings that have to do with cors.

**Comment by MasterOfTheTiger** [comment]
@amazinigmech2418 is this resolved? If so please tell me and close it. If not tell me so we can work on it.

**Comment by amazinigmech2418** [comment]
@MasterOfTheTiger It will only work online.

**Comment by amazinigmech2418** [comment]
@MasterOfTheTiger We still need CaV to be updated...

**Comment by MasterOfTheTiger** [comment]
@amazinigmech2418 I see nothing wrong with the Windows version of the program. You need to either rename the issue and explain further what you are talking about, or we need to close this. 

CaV is updated to the newest version. 3.0.2. It works online and offline (as far as I know). However, none of the translations will render online, but that is a different issue.
