### ISSUE TITLE
Android App

### ISSUE THREAD

**Issue by Pufflegamerz** [heb12/heb12#20]
I made this with android studio. It's REALLY buggy.
https://github.com/Pufflegamerz/heb12_mobile/blob/master/app-debug.apk

**Comment by MasterOfTheTiger** [comment]
Okay. Thanks. Can you upload the source code to GitHub?

**Comment by MasterOfTheTiger** [comment]
@pufflegamerz If you upload the source to GitHub I can fix the problems with it.

**Comment by Pufflegamerz** [comment]
Do you have android studio?

**Comment by MasterOfTheTiger** [comment]
@Pufflegamerz Yes I do.

**Comment by Pufflegamerz** [comment]
I'm at school but I can upload later today.

**Comment by MasterOfTheTiger** [comment]
Thanks! I will make a new repo for it and you can upload it there (I will make you a collaborator).
