### ISSUE TITLE
Error with Custom Require function

### ISSUE THREAD

**Issue by MasterOfTheTiger** [heb12/heb12#4]
I get this error in the console when the custom require script runs: 
`Failed to load file:///home/USERNAME/heb12/app/bible/Hebrews.json: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.`

This is the code: 
<pre>
$.noConflict
            function require(url) {
                var rtrn
             jQuery.ajax({async:false,url: url, success: function(result){
                if(url.search(".json")!==-1) {rtrn= JSON.parse(result);} else if(url.search(".js")!==-1) {rtrn= eval("function() {"+result+"}");} else {
            rtrn= result;
                }
        }});return rtrn;
            }
</pre>

**Comment by MasterOfTheTiger** [comment]
@amazinigmech2418 You need to look at it. We may need a different function.

**Comment by amazinigmech2418** [comment]
@MasterOfTheTiger That's just an API error. It can't load json files in a local system.

**Comment by MasterOfTheTiger** [comment]
So it will work on gh-pages?
