### ISSUE TITLE
Load GH Pages

### ISSUE THREAD

**Issue by amazinigmech2418** [heb12/heb12#5]

**Comment by MasterOfTheTiger** [comment]
What do you mean?

**Comment by amazinigmech2418** [comment]
@MasterOfTheTiger We need to get it on GH Pages.

**Comment by MasterOfTheTiger** [comment]
Oh, yeah. I can do this later.

**Comment by MasterOfTheTiger** [comment]
Okay @amazinigmech2418 I have done it, but there is a problem with it. Open the console after loading https://heb12.github.io/heb12/app/online.html

**Comment by amazinigmech2418** [comment]
@MasterOfTheTiger I fixed the JSON errors!
